// Set created_date and modified_date to string or double
// Laten zien met frequency bars? (frequency bar per status en hoeveel overgeschreven records erbij horen)
LABEL WITH safe WHERE COL(crea_rating_id) = 2
LABEL WITH reasonably_safe WHERE COL(crea_rating_id) = 3
LABEL WITH mild_concern WHERE COL(crea_rating_id) = 4
LABEL WITH concern WHERE COL(crea_rating_id) = 5
FILTER WHERE COL(modified_date) != COL(created_date)