// What time of the day do people enter the measurement?

// Select all records from the mijnnierinzicht table
FILTER WHERE (col(measurement_id) = 346)
// Divide records per hour based on the moment they entered the data into mijnnierinzicht
CHUNK ON COL(created_date) PER HOUR
// Compute for each chunk (so per hour of the day) how many records are present
COMPUTE COUNT(COL(created_date))
// Remove the chunks by adding all records back into one sequence
CHUNK REMOVE