// What are the conditions under which people overwrite their initial data entered in Mijnnierinzicht?

// Label each record with the status the patient currently is in
LABEL WITH safe WHERE COL(crea_rating_id) = 2
LABEL WITH reasonably_safe WHERE COL(crea_rating_id) = 3
LABEL WITH mild_concern WHERE COL(crea_rating_id) = 4
LABEL WITH concern WHERE COL(crea_rating_id) = 5

// Select only all records containing a value entered into mijnnierinzicht which is at least modified once
FILTER WHERE COL(revision) > 1